In [138]:
import pandas as pd
import keras as K
import numpy as np
import matplotlib.pyplot as plt
# matplotlib.use('Agg')
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import cv2
import seaborn as sns
import random
import os

In [139]:
file_name='/content/drive/My Drive/tickets.csv'

In [140]:
data=pd.read_csv('/content/drive/My Drive/tickets.csv')

from sklearn.utils import shuffle
data=shuffle(data)
print(data)

                                                 Title                                         Resolution
183                   FW: Myspace Login Problem - Ania  Go to URL : password.reset.com, Enter you logi...
101          Replace the battery for my Macbook laptop  Please run Battery Helath test and send us the...
190             How do I find the name of my computer?   Right-click My Computer. Click Properties. In...
201                                  Install MS Office  Please login to web mail and go to settings -o...
131        How do I determine the name of my computer?   Right-click My Computer. Click Properties. In...
..                                                 ...                                                ...
38               I am unable to send or receive email?   Verify that your computer is able to see the ...
205                          LAN does not work in a VM  changed network settings to Bridged and config...
31      How can I recover a file from the recy

In [141]:
print(data.iloc[0])


Title                          FW: Myspace Login Problem - Ania
Resolution    Go to URL : password.reset.com, Enter you logi...
Name: 183, dtype: object


In [142]:
#cleaning=>remove specail chars
#Tokenization=> Divide sentence into tokens
#Stop words removal => remove conjunctions
#Lemmatization=> Same like Stem but more accurate
#Stemming=> chaning playing to play

import re
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [143]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [144]:
#stopwords
stop_words=stopwords.words('english')
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [145]:
#Stemming
stemmer=PorterStemmer()
s="There are several types of stemming algorithms"
s=nltk.word_tokenize(s) #tokenization
for w in s:
  print(stemmer.stem(w))

there
are
sever
type
of
stem
algorithm


In [146]:
#Lemmatization
from nltk.stem import WordNetLemmatizer
lemm=WordNetLemmatizer()
snew="There are several types of stemming algorithms"
snew=nltk.word_tokenize(snew)
for i in s:
  print(lemm.lemmatize(i))

There
are
several
type
of
stemming
algorithm


In [147]:
stop_words.append(['é', 'à','de'])
lema=WordNetLemmatizer()
for index,row in data.iterrows():
  final_sen=''
  sen=row['Title']
  sen=re.sub(r'[^\w\s]','',sen) #cleaning
  words=nltk.word_tokenize(sen) #Tokenization
  words=[w for w in words if not w in stop_words] #Stop words removed
  for w in words:
    final_sen=final_sen+' '+lema.lemmatize(w)
  print(final_sen)
  data.loc[index,'Title']=final_sen   #replace with new sen


 FW Myspace Login Problem Ania
 Replace battery Macbook laptop
 How I find name computer
 Install MS Office
 How I determine name computer
 FW Connection issue Myspace Ania
 Install postgres database machine
 My Internet working
 MySpace Password Expiration
 New Account needed new joinee
 My computer turn What I
 How I update Microsoft Windows computer
 The desktop work
 install MS office
 LAN work VM
 New account necessary new member
 Blocked account Do log
 The wheel mouse work correctly I
 How I get safe mode
 Login credetials work
 MySpace password expiration
 I receive email attachment
 I lost printer installation disc I install printer
 I cant receive email attachment
 Why mouse acting erratically
 The My Space QA app
 Install postgres database machine
 How I clean keyboard
 How I get safe mode
 There display monitor I
 MySpace Password Expiry
 Computer getting switched
 How I fix paper jam
 My computer power
 Does Windows come virus protection program
 Given problem network Inte

In [148]:
print(data)

                                                 Title                                         Resolution
183                      FW Myspace Login Problem Ania  Go to URL : password.reset.com, Enter you logi...
101                     Replace battery Macbook laptop  Please run Battery Helath test and send us the...
190                           How I find name computer   Right-click My Computer. Click Properties. In...
201                                  Install MS Office  Please login to web mail and go to settings -o...
131                      How I determine name computer   Right-click My Computer. Click Properties. In...
..                                                 ...                                                ...
38                         I unable send receive email   Verify that your computer is able to see the ...
205                                        LAN work VM  changed network settings to Bridged and config...
31                      How I recover file rec

In [149]:
from sklearn.feature_extraction.text import CountVectorizer


In [150]:
#bag of words: Replace words by their frequency less efficient than tf-idf
vectorizer=CountVectorizer()
try2=['There is a cat', 'The cat is beautiful' ,'There is still hope']
print(try2)
frequency=vectorizer.fit_transform(try2)
print(vectorizer.get_feature_names())
print(frequency.toarray())
vectorizer2=CountVectorizer(analyzer='word',ngram_range=(1,3))
freq2=vectorizer2.fit_transform(try2)
print(vectorizer2.get_feature_names())
print(freq2.toarray())

['There is a cat', 'The cat is beautiful', 'There is still hope']
['beautiful', 'cat', 'hope', 'is', 'still', 'the', 'there']
[[0 1 0 1 0 0 1]
 [1 1 0 1 0 1 0]
 [0 0 1 1 1 0 1]]
['beautiful', 'cat', 'cat is', 'cat is beautiful', 'hope', 'is', 'is beautiful', 'is cat', 'is still', 'is still hope', 'still', 'still hope', 'the', 'the cat', 'the cat is', 'there', 'there is', 'there is cat', 'there is still']
[[0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 1 0]
 [1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 1 1 1 1 0 0 0 1 1 0 1]]


In [151]:
#TF-IDF vectorizer Tf=term freq= freq of word/total words , DF=docuemnt freq= no of docs containign word/total docs IDF= lof(1/DF)
# def dummy(doc):
#   return doc

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizertf=TfidfVectorizer()
X=data['Title']
# data=[line.strip()  for line in data['Title']]
# data=[line.lower() for line in data['Title']]

vector=vectorizertf.fit_transform(X)

In [152]:
print(vectorizertf.get_feature_names())

['able', 'access', 'account', 'act', 'acting', 'address', 'allowed', 'among', 'ania', 'antivirus', 'anymore', 'app', 'appearing', 'appears', 'application', 'are', 'attachment', 'attempt', 'authorization', 'available', 'battery', 'beginning', 'behave', 'behaves', 'behaving', 'bin', 'black', 'blocked', 'bloqueó', 'blue', 'border', 'can', 'cant', 'cause', 'clean', 'client', 'closing', 'come', 'compte', 'computer', 'configuration', 'configure', 'configured', 'connect', 'connection', 'contraseña', 'cooky', 'correctly', 'could', 'crash', 'create', 'credential', 'credetials', 'cuenta', 'damage', 'database', 'de', 'debido', 'delete', 'desktop', 'determine', 'disc', 'disk', 'display', 'distorted', 'do', 'does', 'doesnt', 'drive', 'due', 'eliminate', 'email', 'enter', 'equipped', 'erase', 'erratically', 'ethernet', 'expiration', 'expired', 'expiry', 'faced', 'facing', 'fails', 'favor', 'file', 'find', 'fix', 'forgot', 'forgotten', 'format', 'freeze', 'fw', 'get', 'getting', 'given', 'got', 'hang

In [153]:
print(vector)

  (0, 8)	0.47289297725930424
  (0, 169)	0.45514749721322634
  (0, 123)	0.4156833048717488
  (0, 139)	0.4156833048717488
  (0, 91)	0.47289297725930424
  (1, 119)	0.45255853199259893
  (1, 125)	0.5148432690702106
  (1, 20)	0.5148432690702106
  (1, 179)	0.5148432690702106
  (2, 39)	0.319427043812261
  (2, 140)	0.5684078239084808
  (2, 85)	0.6756042257804868
  (2, 99)	0.34414799070826246
  (3, 151)	0.5970796604634868
  (3, 137)	0.6203588507601436
  (3, 106)	0.5085772068667265
  (4, 60)	0.6277173528894465
  (4, 39)	0.33726731721858305
  (4, 140)	0.6001538866832401
  (4, 99)	0.36336895012734133
  (5, 113)	0.46369145485345037
  (5, 44)	0.48994133028750114
  (5, 8)	0.443330469631156
  (5, 139)	0.38969721190334633
  (5, 91)	0.443330469631156
  :	:
  (231, 174)	0.4418121223216003
  (232, 220)	0.6398003771198055
  (232, 118)	0.6117063376730966
  (232, 227)	0.4652642624228968
  (233, 25)	0.49151706095130016
  (233, 176)	0.49151706095130016
  (233, 84)	0.43205428315136885
  (233, 175)	0.49151706095

In [154]:
#Above was preprocess  now we will build the model

In [155]:
from sklearn import model_selection,preprocessing
from sklearn.metrics import accuracy_score


In [156]:
train_x,valid_x,train_y,valid_y=model_selection.train_test_split(vector,data['Resolution'],test_size=0.1)

In [157]:
print(train_x.shape,valid_x.shape)

(212, 233) (24, 233)


In [158]:
#label Encoding
encoder=preprocessing.LabelEncoder()
train_y=encoder.fit_transform(train_y)
valid_y=encoder.fit_transform(valid_y)

In [159]:
M=vector.toarray()
print(vector)

  (0, 8)	0.47289297725930424
  (0, 169)	0.45514749721322634
  (0, 123)	0.4156833048717488
  (0, 139)	0.4156833048717488
  (0, 91)	0.47289297725930424
  (1, 119)	0.45255853199259893
  (1, 125)	0.5148432690702106
  (1, 20)	0.5148432690702106
  (1, 179)	0.5148432690702106
  (2, 39)	0.319427043812261
  (2, 140)	0.5684078239084808
  (2, 85)	0.6756042257804868
  (2, 99)	0.34414799070826246
  (3, 151)	0.5970796604634868
  (3, 137)	0.6203588507601436
  (3, 106)	0.5085772068667265
  (4, 60)	0.6277173528894465
  (4, 39)	0.33726731721858305
  (4, 140)	0.6001538866832401
  (4, 99)	0.36336895012734133
  (5, 113)	0.46369145485345037
  (5, 44)	0.48994133028750114
  (5, 8)	0.443330469631156
  (5, 139)	0.38969721190334633
  (5, 91)	0.443330469631156
  :	:
  (231, 174)	0.4418121223216003
  (232, 220)	0.6398003771198055
  (232, 118)	0.6117063376730966
  (232, 227)	0.4652642624228968
  (233, 25)	0.49151706095130016
  (233, 176)	0.49151706095130016
  (233, 84)	0.43205428315136885
  (233, 175)	0.49151706095

In [160]:
#Using Logistic Regression for ChatBot
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [161]:
logreg=LogisticRegression(max_iter=300)
logreg.fit(train_x,train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=300,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [162]:
y_pred=logreg.predict(valid_x)
print(y_pred)

[20 45 38 22 33 31 35 36 36 20  1  0 47  3 36 36 39  2 17 23 22 27 44 36]


In [163]:
accuracy_score(y_pred,valid_y)

0.16666666666666666

In [164]:
print(valid_y)

[ 5 17 14  6 10  9 11 12 18  5  1  0 18  3 15 12 13  2  4  7  6  8 16  2]


In [165]:
#decision Tree
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(train_x,train_y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [166]:
pred_tree=dtc.predict(valid_x)


In [167]:
accuracy_score(pred_tree,valid_y)

0.20833333333333334

In [168]:
print(pred_tree)

[20 45 38 22 33 31 35 36 47 20  1  0 47  3 43 36 39  2 17 23 22 27 44  2]


In [169]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(train_x.toarray(),train_y)
# predict_nv=model.predict(valid_x)

GaussianNB(priors=None, var_smoothing=1e-09)

In [170]:
predict_nv=model.predict(valid_x.toarray())

In [171]:
accuracy_score(predict_nv,valid_y)

0.125

In [172]:
print(predict_nv)

[20 45 40 22 33 31 35 36 47 20  1  0 47  6 43 36 39  2 17 45 22 27 44 19]


In [176]:
pd.set_option('display.max_colwidth',1000)
temp=model.predict(vectorizertf.transform(['Wifi not working']).toarray()) 
print(data.loc[temp]['Resolution'])  
temp=model.predict(vectorizertf.transform(['Desktop not working']).toarray()) 
print(data.loc[temp]['Resolution'])                

47     Try restarting your computer. Many basic problems can be resolved easily and quickly this way. Press the Ctrl & Alt & Del keys on your keyboard together at the same time. This should bring up a menu that will allow you to run Task Manager. In Task Manager, switch to the Applications tab. Highlight any programs with the status 'Not Responding' and choose End Task. You may be asked to confirm if you want to end the unresponsive program, so choose Yes. Do this for all programs that are not responding. If all else fails and you cannot shutdown/restart your computer, then hold down the power button on the machine until it forcibly turns off. Wait a few seconds and then turn it back on again. 
Name: Resolution, dtype: object
40     Close all programs running on the computer and try again. If after closing all programs running on the computer you are still encountering the same issue when attempting to delete files, load the computer into Safe Mode and delete the files.
Name: Resolutio

In [174]:
print(data.loc[temp]['Resolution'])

47     Try restarting your computer. Many basic prob...
Name: Resolution, dtype: object
